[2023-09-10T11:13:10.036+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: file_sensor_dag.sense_file scheduled__2023-09-09T00:00:00+00:00 [queued]>
[2023-09-10T11:13:10.046+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: file_sensor_dag.sense_file scheduled__2023-09-09T00:00:00+00:00 [queued]>
[2023-09-10T11:13:10.047+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-09-10T11:13:10.059+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): sense_file> on 2023-09-09 00:00:00+00:00
[2023-09-10T11:13:10.065+0000] {standard_task_runner.py:57} INFO - Started process 496 to run task
[2023-09-10T11:13:10.068+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'file_sensor_dag', 'sense_file', 'scheduled__2023-09-09T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/new_file_sensor_dag.py', '--cfg-path', '/tmp/tmp3qzed3dn']
[2023-09-10T11:13:10.070+0000] {standard_task_runner.py:85} INFO - Job 46: Subtask sense_file
[2023-09-10T11:13:10.123+0000] {task_command.py:415} INFO - Running <TaskInstance: file_sensor_dag.sense_file scheduled__2023-09-09T00:00:00+00:00 [running]> on host 207c7509dcbb
[2023-09-10T11:13:10.195+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='file_sensor_dag' AIRFLOW_CTX_TASK_ID='sense_file' AIRFLOW_CTX_EXECUTION_DATE='2023-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-09T00:00:00+00:00'
[2023-09-10T11:13:10.203+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-10T11:13:10.204+0000] {filesystem.py:64} INFO - Poking for file /opt/***/plugins/WordbankEconomicData_Trimmed_v2.xlsx
[2023-09-10T11:13:20.225+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-10T11:13:20.226+0000] {filesystem.py:64} INFO - Poking for file /opt/***/plugins/WordbankEconomicData_Trimmed_v2.xlsx
[2023-09-10T11:13:30.219+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-10T11:13:30.220+0000] {filesystem.py:64} INFO - Poking for file /opt/***/plugins/WordbankEconomicData_Trimmed_v2.xlsx
[2023-09-10T11:13:40.239+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-10T11:13:40.240+0000] {filesystem.py:64} INFO - Poking for file /opt/***/plugins/WordbankEconomicData_Trimmed_v2.xlsx
[2023-09-10T11:13:50.257+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-10T11:13:50.258+0000] {filesystem.py:64} INFO - Poking for file /opt/***/plugins/WordbankEconomicData_Trimmed_v2.xlsx
[2023-09-10T11:14:00.257+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-10T11:14:00.258+0000] {filesystem.py:64} INFO - Poking for file /opt/***/plugins/WordbankEconomicData_Trimmed_v2.xlsx
[2023-09-10T11:14:10.280+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-10T11:14:10.281+0000] {filesystem.py:64} INFO - Poking for file /opt/***/plugins/WordbankEconomicData_Trimmed_v2.xlsx
[2023-09-10T11:14:10.283+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 268, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.129437523995875 seconds exceeds the specified timeout of 60.0.
[2023-09-10T11:14:10.292+0000] {taskinstance.py:1400} INFO - Immediate failure requested. Marking task as FAILED. dag_id=file_sensor_dag, task_id=sense_file, execution_date=20230909T000000, start_date=20230910T111310, end_date=20230910T111410
[2023-09-10T11:14:10.304+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 46 for task sense_file (Sensor has timed out; run duration of 60.129437523995875 seconds exceeds the specified timeout of 60.0.; 496)
[2023-09-10T11:14:10.342+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-10T11:14:10.369+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
